# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "discounts-king"
client_id = "e3308d898997f187a03e058065a4eece"
application_url = "https://advise-scene-numerous-cyprus.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [
  "https://advise-scene-numerous-cyprus.trycloudflare.com/auth/callback",
  "https://advise-scene-numerous-cyprus.trycloudflare.com/auth/shopify/callback",
  "https://advise-scene-numerous-cyprus.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "myverytestingstore.myshopify.com"
